name: Release
on:
  release:
    types: [published]
jobs:
  zip:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - run: zip -r eirc_spb.zip custom_components/eirc_spb -x "*__pycache__*" "*.DS_Store*"
      - uses: softprops/action-gh-release@v2
        with:
          files: eirc_spb.zip
